kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1
clientConnection:
  kubeconfig: kubeconfig.yaml
profiles:
  - schedulerName: default-scheduler
    plugins:
      filter:
        enabled:
          - name: NodeUnschedulable
          - name: NodeName
          - name: NodePorts
          - name: NodeAffinity
          - name: NodeResourcesFit
          - name: PodTopologySpread
          - name: InterPodAffinity
      score:
        enabled:
          - name: NodeResourcesBalancedAllocation
            weight: 1
          - name: ImageLocality
            weight: 1
          - name: InterPodAffinity
            weight: 1
          - name: NodeResourcesFit
            weight: 1
          - name: NodeAffinity
            weight: 1
          - name: PodTopologySpread
            weight: 2
        disabled:
          - name: TaintToleration
    pluginConfig:
      - name: NodeAffinity
        args:
          kind: NodeAffinityArgs
          apiVersion: kubescheduler.config.k8s.io/v1
      - name: NodeResourcesBalancedAllocation
        args:
          kind: NodeResourcesBalancedAllocationArgs
          apiVersion: kubescheduler.config.k8s.io/v1
          resources:
            - name: cpu
              weight: 1
            - name: memory
              weight: 1
      - name: NodeResourcesFit
        args:
          kind: NodeResourcesFitArgs
          apiVersion: kubescheduler.config.k8s.io/v1
          scoringStrategy:
            type: LeastAllocated
            resources:
              - name: cpu
                weight: 1
              - name: memory
                weight: 1
      - name: PodTopologySpread
        args:
          kind: PodTopologySpreadArgs
          apiVersion: kubescheduler.config.k8s.io/v1
          defaultingType: System
  - schedulerName: qemukvm-scheduler
    plugins:
      filter:
        enabled:
          - name: NodeUnschedulable
          - name: NodeName
          - name: NodePorts
          - name: NodeAffinity
          - name: NodeResourcesFit
          - name: PodTopologySpread
          - name: InterPodAffinity
      score:
        enabled:
          - name: NodeResourcesBalancedAllocation
            weight: 1
          - name: ImageLocality
            weight: 1
          - name: InterPodAffinity
            weight: 1
          - name: NodeResourcesFit
            weight: 1
          - name: NodeAffinity
            weight: 1
          - name: PodTopologySpread
            weight: 2
          - name: QemuKvmAnnotation
            weight: 1
        disabled:
          - name: TaintToleration
    pluginConfig:
      - name: NodeAffinity
        args:
          kind: NodeAffinityArgs
          apiVersion: kubescheduler.config.k8s.io/v1
      - name: NodeResourcesBalancedAllocation
        args:
          kind: NodeResourcesBalancedAllocationArgs
          apiVersion: kubescheduler.config.k8s.io/v1
          resources:
            - name: cpu
              weight: 1
            - name: memory
              weight: 1
      - name: NodeResourcesFit
        args:
          kind: NodeResourcesFitArgs
          apiVersion: kubescheduler.config.k8s.io/v1
          scoringStrategy:
            type: LeastAllocated
            resources:
              - name: cpu
                weight: 1
              - name: memory
                weight: 1
      - name: PodTopologySpread
        args:
          kind: PodTopologySpreadArgs
          apiVersion: kubescheduler.config.k8s.io/v1
          defaultingType: System
      - name: QemuKvmAnnotation
        args:
          kind: QemuKvmArgs
          apiVersion: kubescheduler.config.k8s.io/v1
          qemuKvmScore: 100
          nonQemuKvmScore: 0
          weight: 1